### PR TITLE
Stack images vertically on smaller media

### PR DESCRIPTION
**Pull request by mittaluday**
#### Changes:
- Added a media query 'mq' to check for screen sizes smaller than 640px
- Added a event handler to check for window resize
- Added a function to get image width according to the scenario
- Used the function to generate the image sizes on first init.

Visit [my webpage](http://www.mittaluday.com) for a live example

I see this as a feature on your roadmap, so here's my contribution.

### CODE REVIEW

**Comment by mapsam** [comment]
Awesome! I'm wondering if we can allow the user to override the 640px with their own dimensions, so they can fit their own necessary dimensions. This would essentially become another parameter they can load on init such as:

```
igrid.init({
    container: 'container',
    client_id: '...',
    userID: '...',
    mediaQuery: 960, // default to 640px?
});
```

Glad to see the library is in use on your page - looks great.

**Comment by mittaluday** [comment]
Great idea! Modified the code accordingly. mediaQuery is another parameter now that you can load in your init config. :)

**Comment by mittaluday** [comment]
@mapsam, do you want me to modify the code or something to accept the pull request?  :) Let me know. Thanks!

**Comment by mapsam** [comment]
Ah, sorry I let this slide. Thanks for the bump. :+1:

**Pull request merged**
